services:
  bot:
    build: .
    container_name: rent_apartment_bot
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    restart: always
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: postgres:15
    container_name: students_rent_postgres
    environment:
      POSTGRES_DB: students_rent
      POSTGRES_USER: students_rent_user
      POSTGRES_PASSWORD: students_rent_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local
